stages:
  - approval-check

check_approvals:
  stage: approval-check
  image: curlimages/curl:latest

  before_script:
    - apk add --no-cache jq

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

  script:
    # ① MR approvals API 호출
    - 'RESPONSE=$(curl --silent --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/approvals")'

    # ② 승인 수 추출
    - 'APPROVED=$(echo "$RESPONSE" | jq ".approved_by | length")'

    # ③ 승인 수 검사(2 미만이면 exit 1)
    - 'if [ "$APPROVED" -lt 2 ]; then echo "ERROR: 최소 2개의 승인이 필요합니다. 현재 승인 수: $APPROVED"; exit 1; fi'
