stages:
  - approval-check

check_approvals:
  stage: approval-check
  image: curlimages/curl:latest

  before_script:
    - apk add --no-cache jq

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

  script:
    # 1) Deploy Token 인증으로 MR approvals API 호출
    - 'RESPONSE=$(curl --silent -u "$DEPLOY_USER:$DEPLOY_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/approvals")'

    # 2) 승인 수 파싱
    - 'APPROVED=$(echo "$RESPONSE" | jq ".approved_by | length")'

    # 3) 2명 미만이면 실패
    - 'if [ "$APPROVED" -lt 2 ]; then echo "ERROR: 최소 2개의 승인이 필요합니다. 현재 승인 수: $APPROVED"; exit 1; fi'
