apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarm-service
  namespace: msa-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alarm-service
  template:
    metadata:
      labels:
        app: alarm-service
    spec:
      containers:
        - name: alarm-service
          image: hongbeom1/alarm-service:latest
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: alarm-service
  namespace: msa-apps
spec:
  selector:
    app: alarm-service
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP